vestiaire: supprimer branche du fork - closed #8
spyrales/la-piscine pull request #9
Opened 2020-04-03 14:37 UTC by strainel

2020-04-03 15:10 UTC, RLesur requested changes

2020-04-03 15:10 UTC, RLesur commented on readme.md
> +Voilà c'est (maibntenant) terminé. Bravo !
```suggestion
Voilà c'est (maintenant) terminé. Bravo !
```

2020-04-03 15:11 UTC, RLesur approved these changes

2020-04-03 15:11 UTC, merged

2020-04-03 15:12 UTC, RLesur commented
dsl @Welsh44 , j'ai mergé trop vite...

2020-04-04 14:03 UTC, Welsh44 commented
Pas de souci. J'avais vu le résultat mais pas le request. Sorry.